before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - freebsd
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - -X main.Version={{.Version}}
    main: ./cmd/certify/
brews:
  - name: certify
    homepage: "https://github.com/nothinux/homebrew-tools"
    folder: Formula
    description: "Certify is an easy-to-use certificate manager and can be used as an alternative to OpenSSL. With Certify you can create your own private CA (Certificate Authority) and issue certificates with your own CA"
    license: "MIT"
    repository:
      owner: nothinux
      name: homebrew-tools
      branch: main
      token: "{{ .Env.TAP_TOKEN }}"
    commit_msg_template: "formula update for {{ .ProjectName }} version {{ .Tag }}"
  - name: "certify@{{ .Env.RELEASE_VERSION }}"
    homepage: "https://github.com/nothinux/homebrew-tools"
    folder: Formula
    description: "Certify is an easy-to-use certificate manager and can be used as an alternative to OpenSSL. With Certify you can create your own private CA (Certificate Authority) and issue certificates with your own CA"
    license: "MIT"
    repository:
      owner: nothinux
      name: homebrew-tools
      branch: main
      token: "{{ .Env.TAP_TOKEN }}"
    commit_msg_template: "formula update for {{ .ProjectName }} version {{ .Tag }}"
